# Generated by Django 4.1.1 on 2022-10-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
